import type { CaseStudyContent } from '@/lib/types'

export const tesselloCaseStudy: CaseStudyContent = {
  sections: [
    {
      quote:
        'Existing pattern tools give you pre-baked outputs you can shuffle around. Tessello gives you a parametric engine — and lets you paste any SVG and turn it into a repeatable tile in seconds.',
    },
    {
      title: 'The Problem',
      body: [
        'Every designer has spent hours trying to get the right background pattern.',
        'The existing options all have the same problem: they\'re static. Services like Heropatterns give you a library of pre-baked outputs. Figma\'s native repeat grid gets you partway there. But none of them let you design the pattern — adjust parameters live, stack layers, or bring in your own shapes.',
        'Pattern tools treat patterns as finished things. Tessello treats them as variables.',
        'When Contra and Figma issued a Makeathon challenge to build something genuinely useful for designers, this was the right problem to solve.',
      ],
    },
    {
      title: 'What Tessello Is',
      body: [
        'A parametric pattern engine, built entirely in Figma Make. No plugins. No backend. No local setup. Runs completely in the browser.',
        'You start with a default pattern and adjust from there. Two categories of pattern types:',
        '• Grid · Isometric · Triangle · Voronoi · Wave · Pinwheel · Penrose (8 core patterns)',
        '• Scallop · Moroccan · OG · Cross · Arrow · Dot Matrix · Lozenge · Basket (8+ decorative elements)',
        'These range from the structurally predictable (grid, isometric) to the mathematically unusual — Penrose is aperiodic, tiling infinitely without ever repeating; Voronoi emerges from point proximity rather than a grid.',
      ],
    },
    {
      title: 'The Features That Matter',
      body: [
        '• Pattern Stacking — Stack pattern types on top of one another. Two patterns overlapping create emergent texture. The demo shows a result that reads like industrial steel plate: something you wouldn\'t arrive at by choosing a single pattern type, but that emerges naturally from layering.',
        '• SVG Paste-to-Pattern — Copy any SVG (an icon, a logo mark, a shape from a previous project). Select a layer in Tessello. Ctrl+V. The SVG drops into a 100×100 tile canvas and instantly becomes a repeatable pattern. Any icon becomes a repeating pattern. Any mark becomes a surface system.',
        '• Fully Parametric Controls — Every pattern type exposes live controls. Adjust and see it update in real time.',
        '• Three Export Paths — SVG (editable, scalable), PNG (flat raster for immediate use), Figma-native (drops directly onto canvas as a Figma object).',
      ],
      quote: 'SVG Paste-to-Pattern is the feature that separates Tessello from every other pattern tool. Your logo mark, your icon set, your custom glyphs — all of them become raw material.',
    },
    {
      title: 'Process',
      body: [
        'The constraint was the canvas. Figma Make is a relatively new environment. Building a parametric engine with real-time parameter controls, pattern stacking, and SVG paste — with no backend and no plugins — inside Figma Make required working within its specific constraints and capabilities.',
        'The mathematical pattern choices were deliberate. Including Penrose was a statement: it\'s aperiodic tiling — a mathematical object that most designers have never had access to without writing code. Putting it in a point-and-click interface, alongside grid and isometric, means the range goes all the way from "I need a simple background" to "I want something that\'s genuinely unusual and has mathematical depth."',
        'Voronoi has similar weight. The shape comes from the data — it\'s generated by proximity between points, not defined by a grid. As a result, it produces organic-feeling geometry that holds up to scrutiny because it has underlying logic.',
        'The SVG feature emerged from real designer behavior. Designers have existing assets. The insight that you can treat any icon or shape as a repeating tile means Tessello works for brand systems — not just for decoration.',
      ],
    },
    {
      title: 'Outcome',
      body: [
        'Submitted to the Contra × Figma Makeathon, March 2026. Built and shipped in a compressed sprint. Fully functional pattern engine with 8 core types, 8+ decorative elements, pattern stacking, SVG paste, and three-format export.',
        'Currently live and open for anyone to use.',
      ],
      flow: [
        { label: 'Live tool', description: 'figma.com/make/zV6yrZ1R9fB2Gd712RhSkm' },
        { label: 'Demo video', description: 'youtube.com/watch?v=Kbr4Lq3hU-0' },
        { label: 'Makeathon', description: 'Contra × Figma Makeathon — March 2026' },
      ],
    },
    {
      title: 'What This Demonstrates',
      body: [
        '• Creative Technology depth — Penrose and Voronoi aren\'t Figma tutorials. They\'re mathematical systems brought into a live GUI without code.',
        '• Product instinct — Every feature decision serves a real workflow: stack for complexity, SVG paste for custom marks, three export formats for different downstream uses.',
        '• Toolmaking mindset — Designers who build tools for other designers see design problems differently. Tessello exists because the existing tools were wrong, not because a brief asked for it.',
        '• Execution under constraint — No backend. No plugins. A tight Makeathon window. All of it shipped.',
      ],
    },
    {
      title: 'Documentation In Progress',
      body: [
        'This case study is in active development. Visual documentation — pattern output gallery, UI screenshots, SVG paste workflow, and export format comparisons — will be published here as work continues.',
      ],
    },
  ],
}
